FROM python:3.10-slim

RUN python -m pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir \
        --index-url https://download.pytorch.org/whl/cpu \
        --extra-index-url https://pypi.org/simple \
        torch torchvision && \
    pip install --no-cache-dir \
        timm numpy pillow fvcore

WORKDIR /workspace